POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Artni",
    "number": "0090"
}

###

GET http://localhost:3001/api/persons

//DELETE http://localhost:3001/api/persons/1
