POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "jasmin",
    "number": "0090"
}

###

GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/60a36f6e4ba7234764becd66


###

PUT http://localhost:3001/api/persons/60a36f6e4ba7234764becd66
Content-Type: application/json

{
    "name": "Arttu",
    "number": "33333"
}


//DELETE http://localhost:3001/api/persons/1

###

POST https://boiling-sands-07334.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Artni",
    "number": "0090"
}

###

GET https://boiling-sands-07334.herokuapp.com/api/persons

//DELETE http://localhost:3001/api/persons/1

